#!/bin/sh
xsetroot -solid black &

setxkbmap it
xset b off

xrandr --output eDP1 --set "scaling mode" "Full aspect"
xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode eDP1 1920x1080_60.00
xrandr --output eDP1 --mode 1920x1080_60.00

dwmblocks &
exec dwm

